spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mytodo
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
server:
  port : 8080