spring:
  datasource:
    url: jdbc:postgresql://ec2-54-74-14-109.eu-west-1.compute.amazonaws.com:5432/db7o56opi8bm4
    driver-class-name: org.postgresql.Driver
    username: ENC(L4yGnaJSXQpIOzS6lmsOQFHc6CI19YQB)
    password: ENC(C34z7UypYNYt2GImzXnoNrL4xvPmYGF+vcLObiowM1DzzQM37jTiZfnF4wGmU6Pc8ErY71jw5zS/HJ9v+vJfWKa/r/LBsmZCpZhIBBAlsBk=)
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/changelog.yml
server:
  port : 5000